# Project
mod_version=1.9.3
maven_group=com.github.darkpred.morehitboxes
archives_name=morehitboxes
java_version=21

# Publishing
game_versions=1.20.6

# Common
minecraft_version=1.20.6
minecraft_version_range_lower=1.20.6
minecraft_version_range_upper=1.21
neo_form_version=1.20.6-20240627.102356
parchment_mc_version=1.20.6
parchment_date=2024.06.16
gecko_lib_version=4.5.4

# Forge
neoforge_version=20.6.138
neoforge_version_range=20.6
neoforge_loader_version_range=1

# Fabric
fabric_api_version=0.100.8
fabric_loader_version=0.16.3
fabric_loader_version_range=0.16.3

# Mod options
mod_id=morehitboxes
mod_name=morehitboxes
mod_license=MIT
mod_author=DarkPred
mod_description=An API that adds support for multiple hitboxes that can optionally be controlled by GeckoLib animations

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true