import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'com.modrinth.minotaur' version '2.+'
    id 'net.darkhax.curseforgegradle' version '1.1.25'
}

minecraft {
    mappings channel: 'parchment', version: "$parchment_date-$parchment_mc_version"

    copyIdeResources = true //Calls processResources when in dev

    runs {
        client {
            workingDirectory file('runs/client')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Client'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                modClientRun {
                    source sourceSets.main
                    source project(":common").sourceSets.main
                }
            }
        }

        server {
            workingDirectory file('runs/server')
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName 'Server'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                modServerRun {
                    source sourceSets.main
                    source project(":common").sourceSets.main
                }
            }
        }

        data {
            workingDirectory file('runs/data')
            ideaModule "${rootProject.name}.${project.name}.main"
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            taskName 'Data'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                modDataRun {
                    source sourceSets.main
                    source project(":common").sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    minecraft "net.minecraftforge:forge:$minecraft_version-$forge_version"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1")
    implementation jarJar("io.github.llamalad7:mixinextras-forge:0.4.1") {
        jarJar.ranged(it, "[0.4.1,)")
    }

    compileOnly fg.deobf("software.bernie.geckolib:geckolib-forge-$minecraft_version:$gecko_lib_version")
    compileOnly "com.eliotlash.mclib:mclib:20"

    compileOnly annotationProcessor('com.google.auto.service:auto-service:1.1.1')
}

mixin {
    add sourceSets.main, "mixins.${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

jar {
    setArchiveClassifier('slim')
}
tasks.jarJar {
    setArchiveClassifier('')
}

jar.finalizedBy('reobfJar')
tasks.jarJar.finalizedBy('reobfJarJar')

modrinth {
    token = "${project.property("MODRINTH_TOKEN")}" ?: "no value"
    projectId = "BOVAW87Z"
    versionNumber.set("$minecraft_version-$mod_version-${project.name}")
    versionType.set("release")
    uploadFile.set(tasks.jarJar)
    versionName = "$mod_version for Forge $minecraft_version"
    gameVersions = game_versions.split(",").toList()
    debugMode = true
    dependencies {
        optional.project("geckolib")
    }
    changelog.set(rootProject.file("CHANGELOG.md").text)
}
tasks.register('publishCurseForge', TaskPublishCurseForge) {
    group = "publishing"
    description = "Publishes jar to CurseForge"
    apiToken = project.property("CURSEFORGE_TOKEN") ?: "no value"
    debugMode = true
    var mainFile = upload(1115989, tasks.jarJar)
    mainFile.addGameVersion(game_versions.split(","))
    mainFile.displayName = "$mod_version for Forge $minecraft_version"
    mainFile.changelog = rootProject.file("CHANGELOG.md").text
    mainFile.changelogType = "markdown"
    mainFile.releaseType = "release"
    mainFile.addOptional("geckolib")
}

tasks.named("publish") {
    finalizedBy("modrinth", "publishCurseForge")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId "$archives_name-${project.name}-$minecraft_version"
            version version
            artifact tasks.jarJar
            from components.java
            pom.withXml {
                asNode().dependencies.dependency.each { dep ->
                    if(dep.artifactId.last().value().last() in ["forge", "mixinextras-forge"]) {
                        assert dep.parent().remove(dep)
                    }
                }
            }
        }
    }

    repositories {
        if (project.hasProperty("cloudsmith_username") && project.hasProperty("cloudsmith_token")) {
            maven {
                name = "Cloudsmith"
                url = "https://maven.cloudsmith.io/darkpred-mods/more-hitboxes/"
                credentials {
                    username = project.property("cloudsmith_username")
                    password = project.property("cloudsmith_token")
                }
            }
        } else {
            mavenLocal()
        }
    }
}
