plugins {
    id 'multiloader-common'
    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT'
}

minecraft {
    version(minecraft_version)
}

dependencies {
    compileOnly "software.bernie.geckolib:geckolib-forge-$minecraft_version:$gecko_lib_version"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId "${archives_name}-${project.name}-${minecraft_version}"
            version version
            from components.java
        }
    }

    repositories {
        if (project.hasProperty("cloudsmith_username") && project.hasProperty("cloudsmith_token")) {
            maven {
                name = "Cloudsmith"
                url = "https://maven.cloudsmith.io/darkpred-mods/more-hitboxes/"
                credentials {
                    username = project.property("cloudsmith_username")
                    password = project.property("cloudsmith_token")
                }
            }
        } else {
            mavenLocal()
        }
    }
}