import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev' version '2.0.107'
    id 'com.modrinth.minotaur'
    id 'net.darkhax.curseforgegradle'
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = parchment_mc_version
        mappingsVersion = parchment_date
    }

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            logLevel = org.slf4j.event.Level.DEBUG
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }
    mods {
        "$mod_id" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly "software.bernie.geckolib:geckolib-neoforge-$minecraft_version:$gecko_lib_version"

    compileOnly annotationProcessor('com.google.auto.service:auto-service:1.1.1')
}

modrinth {
    token = "${project.property("MODRINTH_TOKEN")}" ?: "no value"
    projectId = "BOVAW87Z"
    versionNumber.set("$minecraft_version-$mod_version-${project.name}")
    versionType.set("release")
    uploadFile.set(tasks.jarJar)
    versionName = "$mod_version for NeoForge $minecraft_version"
    gameVersions = game_versions.split(",").toList()
    loaders = ["neoforge"]
    debugMode = true
    dependencies {
        optional.project("geckolib")
    }
    changelog.set(rootProject.file("CHANGELOG.md").text)
}
tasks.register('publishCurseForge', TaskPublishCurseForge) {
    group = "publishing"
    description = "Publishes jar to CurseForge"
    apiToken = project.property("CURSEFORGE_TOKEN") ?: "no value"
    debugMode = true
    var mainFile = upload(1115989, tasks.jarJar)
    mainFile.addGameVersion(game_versions.split(","))
    mainFile.addModLoader("NeoForge")
    mainFile.displayName = "$mod_version for NeoForge $minecraft_version"
    mainFile.changelog = rootProject.file("CHANGELOG.md").text
    mainFile.changelogType = "markdown"
    mainFile.releaseType = "release"
    mainFile.addOptional("geckolib")
}

tasks.named("publish") {
    finalizedBy("modrinth", "publishCurseForge")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId "$archives_name-${project.name}-$minecraft_version"
            version version
            from components.java
            pom.withXml {
                asNode().dependencies.dependency.each { dep ->
                    /*if(dep.artifactId.last().value().last() in ["forge", "mixinextras-forge"]) {
                        assert dep.parent().remove(dep)
                    }*/
                }
            }
        }
    }

    repositories {
        if (project.hasProperty("cloudsmith_username") && project.hasProperty("cloudsmith_token")) {
            maven {
                name = "Cloudsmith"
                url = "https://maven.cloudsmith.io/darkpred-mods/more-hitboxes/"
                credentials {
                    username = project.property("cloudsmith_username")
                    password = project.property("cloudsmith_token")
                }
            }
        } else {
            mavenLocal()
        }
    }
}
