name: Publish on GitHub, CurseForge & Modrinth

on: [ pull_request, workflow_dispatch, push ]

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Get properties
        run: |
          echo "$(cat $GITHUB_WORKSPACE/gradle.properties | grep mod_version=)" >> "$GITHUB_ENV"
          echo "$(cat $GITHUB_WORKSPACE/gradle.properties | grep minecraft_version=)" >> "$GITHUB_ENV"
          echo "$(cat $GITHUB_WORKSPACE/gradle.properties | grep minecraft_version_range=)" >> "$GITHUB_ENV"

      - name: Publish Fabric (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          #curseforge-id: 973456
          #curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"
          game-versions: ${{env.minecraft_version_range}}

          #modrinth-id: 1q2w3e4r
          #modrinth-token: "${{env.MODRINTH_TOKEN}}"
          files: |
            Fabric/build/libs/!(*-@(javadoc|sources)).jar
            Fabric/build/libs/*-@(javadoc|sources).jar
            
          github-generate-changelog: true
          github-tag: fabric-${{env.minecraft_version}}-${{env.mod_version}}
          github-token: ${{env.GITHUB_TOKEN}}

          name: More Hitboxes ${{env.mod_version}} for Minecraft ${{env.minecraft_version}}
          version: ${{env.mod_version}}
          #version-type: release
          #changelog-file: CHANGELOG.md                                      #The file in which the changes of your new update are specified (the path starts at your project root)

          loaders: fabric
          java: ${{env.JAVA_VERSION}}